vim.g.user_emmet_leader_key = ','
--vim.g.user_emmet_settings = {
--
--
--local nvim_lsp = require 'lspconfig'
--local configs = require 'lspconfig/configs'
--local capabilities = vim.lsp.protocol.make_client_capabilities()
--local on_attach = function(client, bufnr)
--capabilities.textDocument.completion.completionItem.snippetSupport = true
--
--configs.emmet_ls = {
--  default_config = {
--    cmd = {'emmet-ls, [[--stdio]]'};
--    filetypes = {'html', 'css', 'eruby'};
--    root_dir = function()
--      return vim.loop.cwd()
--    end;
--    settings = {};
--  };
--}
--
--nvim_lsp.emmet_ls.setup{
--  on_attach = on_attach;
--}
