require('smithwebdev.plugins.config.compe')
require('smithwebdev.plugins.config.emmet')
require('smithwebdev.plugins.config.lsp')
require('smithwebdev.plugins.config.lspinstall')
require('smithwebdev.plugins.config.treesitter')
require('smithwebdev.plugins.config.nvim-tree')
