--require 'nvim-treesitter.configs'.setup{
--	ensure_installed = {
--	'css',
--	'html',
--	'javascript',
--	'json',
--	'lua',
--	'python',
--	'tsx',
--	'typescript',
--	'ruby',
--	},
--	highlight = {
--                enable = true,
--                additional_vim_regex_highlighting = true
--        }
--}
